### ISSUE TITLE
수정사항들

### ISSUE THREAD

**Issue by joonseokhu** [wecode-bootcamp-korea/11-PrettyCloud-backend#2]
PR이 너무 오랫동안 묶여있어서 merge 하긴 했는데, 다음 PR에서 두가지 수정 부탁드립니다!

1. 환경변수 중 웹서버 포트는 DB와 관련 없습니다. DB 접두어 없이 그냥 `PORT` 입니다

2. 제가 sequelize 사용하면서 Enum 이런 식으로 잡고 썼었는데 한번 사용해보시고 잘 되시면 적용해보세요

```js
// .. 생략
article_status: {
    type: DataTypes.ENUM(['draft', 'removed', 'public']),
    defaultValue: 'draft',
},
// .. 생략
```

**Comment by LeeHoHyun-hemtory** [comment]
넵
서버포트는 DB 지우겠습니다

`ENUM` 타입은 타입정할때 값을 미리 넣어줘야되는군요
그냥 ENUM타입만 써서 안됐던거 같습니다
한번 해보겠습니다

감사합니다
